IKEO/Models/Commande.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.ArticleCommande = new HashSet<ArticleCommande>();
        }
    
        public int id { get; set; }
        public string numero_commande { get; set; }
        public double prix_commande { get; set; }
        public double etat_livraison { get; set; }
        public bool etat_paiement { get; set; }
        public long id_panier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleCommande> ArticleCommande { get; set; }
        public virtual Panier Panier { get; set; }
    }
}

IKEO/Controllers/CompteController.cs
using System.Web.Mvc;
using IKEO.Models;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System;
using System.Globalization;

namespace IKEO.Controllers
{
    public class CompteController : Controller
    {
        IkeoDBEntities db = new IkeoDBEntities();

        public ActionResult Index()
        {
            var idUtilisateurCourant = Convert.ToInt32(Session["UserID"]);
            var utilisateur = db.Utilisateur.FirstOrDefault(x => x.id == idUtilisateurCourant);
            ViewBag.infoUtilisateur = utilisateur;
            return View();
        }

        public ActionResult Connexion()
        {
            return View();
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "None")]
        public ActionResult RedirigerCreerCompte()
        {
            return View("CreerCompte");
        }

        public ActionResult InformationsPaiement()
        {
            var idUtilisateurCourant = Convert.ToInt32(Session["UserID"]);
            var utilisateur = db.Utilisateur.FirstOrDefault(x => x.id == idUtilisateurCourant);
            
            if (utilisateur.id_cartebancaire != null)
            {
                var cbUtilisateur = db.CarteBancaire.FirstOrDefault(x => x.id == utilisateur.id_cartebancaire);
                ViewBag.cbUtilisateur = cbUtilisateur;
            }
            else
            {
                ViewBag.cbUtilisateur = null;
            }

            ViewBag.utilisateur = utilisateur;
            
     
            return View();
        }
        public ActionResult DownloadPDF()
        {
            // Logique pour générer le fichier PDF à partir de l'identifiant "id"
            // Assurez-vous que le chemin d'accès au fichier PDF est correctement défini

            string filePath = "C:\\SupDeVinci\\Gantt.pdf";
            string fileName = "Gantt.pdf";

            // Téléchargement du fichier
            byte[] fileBytes = System.IO.File.ReadAllBytes(filePath);
            return File(fileBytes, "application/pdf", fileName);
        }

        public ActionResult MotDePasse()
        {
            return View();
        }
        public ActionResult Commande()
        {
            return View();
        }
        public ActionResult CommandeDetails()
        {
            return View();
        }
        public ActionResult Information()
        {
            var idUtilisateurCourant = Convert.ToInt32(Session["UserID"]);
            var utilisateur = db.Utilisateur.FirstOrDefault(x => x.id == idUtilisateurCourant);
            ViewBag.infoUtilisateur = utilisateur;
            return View();
        }
        public ActionResult Deconnecter()
        {
            Session["UserID"] = null;
            Session["UserNom"] = null;
            Session["UserPrenom"] = null;
            return RedirectToAction("Index", "Home");
        }

        public JsonResult Connecter(string email, string password)
        {
            //Faire algorithme de hashage pour password
            string passwordHash = hashPassword(password);
            var utilisateur = db.Utilisateur.FirstOrDefault(x => (x.email == email) && (x.mdp == passwordHash));
            if(utilisateur != null)
            {
                //if(utilisateur.confirm != null || utilisateur.confirm != false) return Json(new { type = "error", message = "Utilisateur non-confirmé" }, JsonRequestBehavior.AllowGet);
                Session["UserID"] = utilisateur.id;
                Session["UserNom"] = utilisateur.nom;
                Session["UserPrenom"] = utilisateur.prenom;
                return Json(new { type="ok", message="Utilisateur connecté"}, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { type = "error", message = "E-mail ou mot de passe incorrect !" }, JsonRequestBehavior.AllowGet);
            }
        }
        private bool CheckInfo(string info)
        {
            if (info.Replace(" ", "") != "") return true;
            else return false;
        }
        
        

        private string hashPassword(string text, string salt = "52aZe")
        {
            using (var sha = new System.Security.Cryptography.SHA256Managed())
            {
                // Convert the string to a byte array first, to be processed
                byte[] textBytes = System.Text.Encoding.UTF8.GetBytes(text + salt);
                byte[] hashBytes = sha.ComputeHash(textBytes);

                // Convert back to a string, removing the '-' that BitConverter adds
                string hash = BitConverter
                    .ToString(hashBytes)
                    .Replace("-", String.Empty);

                return hash;
            }
        }

        public JsonResult CreerCompte(string civilite, string prenom, string nom, string email, string password, string passwordCheck)
        {
            if(CheckInfo(civilite) && CheckInfo(prenom) && CheckInfo(nom) && CheckInfo(email) && CheckInfo(password) && CheckInfo(passwordCheck))
            {
           

                string passwordHash = hashPassword(password);
                string passwordCheckHash = hashPassword(passwordCheck);

                if (passwordHash != passwordCheckHash) return Json(new { type = "error", message = "Les mots de passe ne correspondent pas !" }, JsonRequestBehavior.AllowGet);

                if (db.Utilisateur.Any(x => x.email == email)) return Json(new { type = "error", message = "Ce compte existe déjà !" }, JsonRequestBehavior.AllowGet);

                Panier newPanier = new Panier();

                Utilisateur nouvelUtilisateur = new Utilisateur()
                {
                    email = email,
                    mdp = passwordHash,
                    nom = nom,
                    prenom = prenom,
                    confirm = false,
                    id_cartebancaire = null,
                    Panier = newPanier,
                    Roles = db.Roles.FirstOrDefault(x => x.designation == "Utilisateur"),
                    civilite = civilite
                };

                db.Panier.Add(newPanier);
                db.Utilisateur.Add(nouvelUtilisateur);
                db.SaveChanges();

                return Json(new { type = "ok", message = "Compte créé" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { type = "error", message = "Erreur au niveau des informations, veuillez vérifier celles-ci !" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AjouterAdresse(string nom, string prenom, string adresse, string ville, string code)
        {
            if (Session["UserID"] == null)
                return Json(new { type = "error", message = "Erreur au niveau des informations, veuillez vérifier celles-ci !" }, JsonRequestBehavior.AllowGet);

            if (nom.Replace(" ", "") != "" && prenom.Replace(" ", "") != "" && adresse.Replace(" ", "") != "" && ville.Replace(" ", "") != "" && code.Replace(" ", "") != "")
            {
                var codePo = decimal.Parse(code, CultureInfo.InvariantCulture);

                if (db.Adresse.Any(x => x.adresse1 == adresse && x.Utilisateur.prenom == prenom && x.Utilisateur.nom == nom && x.codepostal == codePo))
                    return Json(new { type = "error", message = "Adresse déja existante !" }, JsonRequestBehavior.AllowGet);

                var adr = new Adresse()
                {
                    codepostal = codePo,
                    adresse1 = adresse,
                    id_utilisateur = int.Parse(Session["UserID"].ToString())
                };
                db.Adresse.Add(adr);

                db.SaveChanges();
                return Json(new { type = "ok", message = "Adresse créé", idAdresse = adr.id }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { type = "error", message = "Erreur au niveau des informations, veuillez vérifier celles-ci !" }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult VerifierAdresse(int idAd)
        {
            if (Session["UserID"] == null)
                return Json(new { type = "error", message = "Erreur au niveau des informations, veuillez vérifier celles-ci !" }, JsonRequestBehavior.AllowGet);

            var idUs = int.Parse(Session["UserID"].ToString());
            if (db.Utilisateur.Any(x => x.id == idUs && x.Adresse.Any(y => y.id == idAd))){
                return Json(new { type = "ok", message = "Adresse retrouvée", idAdresse = idAd }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { type = "error", message = "Erreur au niveau des informations, veuillez vérifier celles-ci !" }, JsonRequestBehavior.AllowGet);
        }
    }
}

IKEO/Views/Compte/Commande.cshtml
@{
    ViewData["Title"] = "Mes commandes";
}

<h3>Mes commandes</h3>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="flex-grow-1 mx-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <h5 class="card-title font-weight-bold">Commande n°A42451</h5>
                                <p class="font-weight-bold">200$</p>
                            </div>
                            <p class="card-text">En cours de livraison</p>
                            <div class="mr-auto">
                                <button class="btn btn-info" onclick="location.href='@Url.Action("CommandeDetails","Compte")'">Voir en détails</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

IKEO/Views/Compte/CommandeDetails.cshtml
<h3>Mes commandes</h3>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="d-flex">
                        <div class="flex-grow-1 mx-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <h5 class="card-title font-weight-bold">Commande n°A42451</h5>
                                <p class="font-weight-bold">200$</p>
                            </div>
                            <p class="card-text">En cours de livraison</p>
                            <p class="card-text">Adresse de livraison</p>
                            <p class="card-text">Ugo Marin</p>
                            <p class="card-text">435 chemin du pré namet</p>
                            <p class="card-text">3500, Rennes</p>
                            <div class="row">
                                <p class="card-text">Détails de votre commande</p>
                                <button class="btn btn-info"  onclick="window.location.href='@Url.Action("DownloadPDF", "Compte")'">Télécharger la facture</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
</script>

IKEO/Views/Compte/Connexion.cshtml
@*
    * Authors: Ugo MARIN, Matéo BATISTA GOMES
    * Date: 08/11/2022
*@
@{
    ViewData["Title"] = "Connexion";
}
<div class="fil-ariane">
    <h2>Authentification</h2>
    <hr />
</div>

<div class="d-flex justify-content-center">
    <form method="post" action="" class="form-login mx-3 w-35 border border-1 border-dark rounded-3 p-2 px-3 mb-1">
        <h3 class="text-center pt-2 pb-3">Login</h3>

        @* INPUT TEXT *@

        <div class="d-flex justify-content-between border border-1 border-dark rounded-3 p-2 mb-3">
            <label class="p-1 bg-light rounded font-size-sm">E-mail</label>
            <input class="w-75" type="text" id="email" />
        </div>
        <div class="d-flex justify-content-between border border-1 border-dark rounded-3 p-2">
            <label class="p-1 bg-light rounded font-size-sm">Mot de passe</label>
            <input type="password" class="w-75" />
        </div>
        <a href="#"><small>Réinitialiser le mot de passe ?</small></a>

        @* CHECKBOX + BOUTON SIGN IN *@

        <div class="d-flex justify-content-between pt-3 pb-4">
            <div class="my-auto">
                <input class="position-relative align-middle" type="checkbox" />
                <label>Se souvenir de moi</label>
            </div>
            <button type="button" class="btn btn-dark sign-in text-white rounded-2 p-2 w-25">Connexion</button>
        </div>

        @* BOUTON DE CONNEXION FACEBOOK / GOOGLE *@

        <div class="d-flex flex-column align-items-center">
            <button type="button" class="btn btn-facebook d-flex align-items-center justify-content-center w-75 mb-3 py-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook me-2" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                </svg>
                Sign in with Facebook
            </button>
            <button type="button" class="btn btn-primary d-flex align-items-center justify-content-center w-75 mb-3 py-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google me-2" viewBox="0 0 16 16">
                    <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z" />
                </svg>
                Sign in with Google
            </button>
        </div>
        <div class="d-flex justify-content-between">
            <hr /> <span>ou</span> <hr />
        </div>
        <div class="d-flex justify-content-center"><a href="@Url.Action("RedirigerCreerCompte", "Compte")">Créer un compte</a></div>
    </form>
</div>

<script>

    function demandeDeConnexion() {
        console.log("tet")
        let DOMEmail = $('#email');
        let DOMPassword = $('input[type="password"]');

        if ((DOMEmail.val() === undefined || DOMEmail.val().replace(/ /g, '') == "") && (DOMPassword.val() === undefined || DOMPassword.val().replace(/ /g, '') == "")) {
            DOMEmail.addClass("border-danger");
            DOMPassword.addClass("border-danger");
            return -1;
        }
        else if ((DOMEmail.val() === undefined || DOMEmail.val().replace(/ /g, '') == "")) {
            DOMEmail.addClass("border-danger");
            DOMPassword.addClass("border-danger");
            return -1
        }
        else if ((DOMPassword.val() === undefined || DOMPassword.val().replace(/ /g, '') == "")) {
            DOMEmail.addClass("border-danger");
            DOMPassword.addClass("border-danger");
            return -1
        }
        else {
            DOMEmail.removeClass("border-danger");
            DOMPassword.removeClass("border-danger");
            $.ajax({
                url: "@Url.Action("Connecter","Compte")",
                data: {
                    email: DOMEmail.val().replace(/ /g, ''),
                    password: DOMPassword.val().replace(/ /g, '')
                },
                success: function (reponseBackEnd) {
                    if (reponseBackEnd.type == "ok")
                        location.href = '@Url.Action("Index","Compte")'
                    if (reponseBackEnd.type == "error") {
                        DOMEmail.addClass("border-danger");
                        DOMPassword.addClass("border-danger");
                    }
                }
            });
        }
    }
    $('.sign-in').on('click', demandeDeConnexion)


    $("form").on("submit", function (e) {
        e.preventDefault();
        demandeDeConnexion()
    });
</script>

IKEO/Views/Compte/CreerCompte.cshtml
@*
    * Authors: Ugo MARIN, Matéo BATISTA GOMES
    * Date: 08/11/2022
*@
@{
    ViewData["Title"] = "Créer un compte";
}
<div class="fil-ariane">
    <h2>Créer un compte</h2>
    <hr />


    <form>
        <div class="mb-3">
            <label for="civilite" class="form-label">Civilité</label>
            <select id="civilite" class="form-select">
                <option hidden selected></option>
                <option value="Autre">Autre</option>
                <option value="M">M</option>
                <option value="Mme">Mme</option>
                <option value="---">Ne pas renseigner</option>
            </select>
            <p class="d-none fs-6 fw-light text-danger">Civilite est nécéssaire</p>
        </div>

        <div class="mb-3">
            <label for="prenom" class="form-label">Prénom:</label>
            <input type="text" class="form-control" id="prenom">
        </div>

        <div class="mb-3">
            <label for="nom" class="form-label">Nom:</label>
            <input type="text" class="form-control" id="nom">
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Adresse email:</label>
            <input type="email" class="form-control" id="email">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Mot de passe:</label>
            <input type="password" class="form-control" id="password">
        </div>
        <div class="mb-3">
            <label for="confirmPassword" class="form-label">Confirmation mot de passe:</label>
            <input type="password" class="form-control" id="confirmPassword">
            <p class="d-none fs-6 fw-light text-danger">Le mot de passe n'est pas le même</p>
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="button" id="creerCompteBtn" class="btn btn-primary">Créer le compte</button>
    </form>

</div>
<script>
    $('#creerCompteBtn').on('click', function () {
        let civilite = $('#civilite');
        let prenom = $('#prenom');
        let nom = $('#nom');
        let adresseEmail = $('#email');
        let password = $('#password');
        let passwordCheck = $('#confirmPassword');

        let peutCreerCompte = true;

        if (password.val() != passwordCheck.val()) {
            $('#confirmPassword').parent().find("p").removeClass("d-none");
            peutCreerCompte = false;
        }
        let informationIndividu = [
            civilite,
            prenom,
            nom,
            adresseEmail,
            password,
            passwordCheck
        ]
        informationIndividu.forEach(function (e) {
            e.removeClass("border-danger");
            if (!checkIfEmpty(e.val())) {
                peutCreerCompte = false;
                e.addClass("border-danger");
            }
        });

        if (peutCreerCompte) {
            $.ajax({
                url: "@Url.Action("CreerCompte", "Compte")",
                data: {
                    civilite: civilite.val(),
                    prenom: prenom.val(),
                    nom: nom.val(),
                    email: adresseEmail.val(),
                    password: password.val(),
                    passwordCheck: passwordCheck.val(),
                },
                success: function (reponseBackEnd) {
                    if (reponseBackEnd.type == "ok") {
                        $.ajax({
                            url: "@Url.Action("Connecter","Compte")",
                            data: {
                                email: adresseEmail.val(),
                                password: password.val()
                            },
                            success: function (reponseBackEnd) {
                                if (reponseBackEnd.type == "ok")
                                    location.href = '@Url.Action("Index","Compte")'
                          
                            }
                        })
                    }
                }
            });
        }

    });


    function checkIfEmpty(valeur) {
        if (valeur === undefined || valeur.replace(/ /g, '') == "") {
            return false;
        }
        else {
            return true;
        }
    }

    $("#confirmPassword").on("blur", function () {
        if ($("#confirmPassword").val() != $("#password").val()) {
            $('#confirmPassword').parent().find("p").removeClass("d-none");
        }
        else {
            $('#confirmPassword').parent().find("p").addClass("d-none");
        }

    });
    //Du style
    $('#civilite').on('blur', function () {
        let civilite = $('#civilite').val();
        if (civilite === undefined || civilite == "") {
            $('#civilite').parent().find("p").removeClass("d-none");
        }
    });
    $("#civilite").on("change", function () {
        let civilite = $('#civilite').val();
        if (civilite != "") {
            $('#civilite').parent().find("p").addClass("d-none");
        }
    });




</script>

IKEO/Views/Compte/Index.cshtml
@{
    ViewData["Title"] = "Index";
    var utilisateur = ViewBag.infoUtilisateur;
}

@if (utilisateur != null && Convert.ToInt32(Session["UserID"]) == utilisateur.id)
{
   
    <div class="d-flex justify-content-center h-100 mt-5">
        <h3>Bonjour @Session["UserPrenom"] @Session["UserNom"]</h3>
    </div>

}

IKEO/Views/Compte/Information.cshtml
@{
    ViewData["Title"] = "Informations personnelles";
    var utilisateur = ViewBag.infoUtilisateur;
}

<h3 class="text-center pb-3">Informations personnelles</h3>

<div class="d-flex flex-column align-items-center gap-3">
    <div class="w-50">
        <label for="staticCivilite">Civilité</label>
        <input id="staticCivilite" type="text" readonly value="@utilisateur.civilite" class="form-control">
    </div>
    <div class="w-50">
        <label for="staticPrenom">Prénom</label>
        <input id="staticPrenom" type="text" readonly value="@utilisateur.prenom" class="form-control">
    </div>
    <div class="w-50">
        <label for="staticNom">Nom</label>
        <input id="staticNom" type="text" readonly value="@utilisateur.nom" class="form-control">
    </div>
    <div class="w-50">
        <label for="staticEmail">Email</label>
        <input id="staticEmail" type="text" readonly value="@utilisateur.email" class="form-control">
    </div>
</div>

@*<div class="container">
    <div class="row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
        <div class="col-sm-10">
            <input type="text" readonly value="@utilisateur.email" class="form-control">
        </div>
        <label for="staticEmail" class="col-sm-2 col-form-label">Civilité</label>
        <div class="col-sm-10">
            <input type="text" readonly value="@utilisateur.civilite" class="form-control">
        </div>
        <label for="staticEmail" class="col-sm-2 col-form-label">Nom</label>
        <div class="col-sm-10">
            <input type="text" readonly value="@utilisateur.prenom" class="form-control">
        </div>
        <label for="staticEmail" class="col-sm-2 col-form-label">Prénom</label>
        <div class="col-sm-10">
            <input type="text" readonly value="@utilisateur.nom" class="form-control">
        </div>
    </div>
</div>*@

IKEO/Views/Compte/InformationsPaiement.cshtml
@{
    ViewData["Title"] = "Mes cartes de paiement";
}

<h3 class="text-center pb-3">Mes cartes de paiement</h3>

<div class="d-flex flex-column align-items-center gap-3">
    <div class="w-50">
        <label for="staticCbNom">Nom de la carte</label>
        <input id="staticCbNom" type="text" readonly value="La carte" class="form-control">
    </div>
    <div class="w-50">
        <label for="staticCbNumero">Numéro de carte</label>
        <input id="staticCbNumero" type="text" readonly value="1234 5085 9652 3158" class="form-control">
    </div>
    <div class="d-flex gap-3 w-50">
        <div class="w-100">
            <label for="staticCbDateValidite">Date de validité</label>
            <input id="staticCbDateValidite" type="text" readonly value="05/24" class="form-control">
        </div>
        <div class="w-100">
            <label for="staticCbCryptogramme">Cryptogramme</label>
            <input id="staticCbCryptogramme" type="password" readonly value="123" class="form-control">
        </div>
    </div>
</div>

IKEO/Views/Compte/MotDePasse.cshtml
@{
    ViewData["Title"] = "Mot de passe";
}

<h3 class="text-center pb-3">Mot de passe</h3>

<form>
    <div class="d-flex flex-column align-items-center gap-3">
        <div class="w-50">
            <label for="ancienMdp">Ancien mot de passe</label>
            <input id="ancienMdp" type="password" class="form-control">
        </div>
        <div class="w-50">
            <label for="nouveauMdp">Nouveau mot de passe</label>
            <input id="nouveauMdp" type="password" class="form-control">
        </div>
        <div class="w-50">
            <label for="confirmationNouveauMdp">Confirmation du nouveau mot de passe</label>
            <input id="confirmationNouveauMdp" type="password" class="form-control">
        </div>
        <button type="submit" class="btn btn-primary w-50">Valider</button>
    </div>
</form>